### ISSUE TITLE
Character Invisible after dungeon cinematic

### ISSUE THREAD

**Issue by Megasder** [shaeeee/Customivisualizer#1]
Hi, I just discovered your plugin and im loving it, however it seems it has a problem, when im in a dungeon,raid,etc and it has any cinematic (like the dungeon final boss scene) the character becomes invisible except the weapon, after you exit the dungeon it works fine again. I hope this can be fixed :)

**Comment by shaeeee** [comment]
Glad to hear you are enjoying the plugin! I'm working on a fix right now, but to narrow things down a bit I'd like to ask if there was any specific duty this occurred in, or if this happened to you in every duty.

**Comment by Megasder** [comment]
I can't say that it happens in every duty, but all the ones I tried it makes my character invisible. 
I noticed another thing in tam-tara deepcroft it makes some enemies look like me lol (it seems its only the first 2 enemies)
![image](https://user-images.githubusercontent.com/92712466/167293133-643d57c9-4dbc-40f7-87f5-8ec9e287f344.png)

Edit: I don't know why but now it becomes invisible for a split second like before but it instantly fixes itself, so all works fine. did you update it?

**Comment by Megasder** [comment]
![image](https://user-images.githubusercontent.com/92712466/167311377-0d6393ef-d5c9-4a3f-8bf2-1fe034bb0520.png)
nevermind, it happened in aglaia XD

Edit: just in case it happened also in Sastasha 
![image](https://user-images.githubusercontent.com/92712466/167312010-51ae506d-9324-4523-92b0-34b7daa74ae6.png)

**Comment by shaeeee** [comment]
Gotcha, thanks for the updates. I'm working on a fix right now, but I will release a new update as soon as its done.

**Comment by shaeeee** [comment]
A new update has been released! If this specific issue does not occur for you again I'll close this issue.

**Comment by Megasder** [comment]
I have been using it and so far no problems, ty :)

**Comment by Megasder** [comment]
nevermind it still happens. with MEM, Classic or Hook after thornmarch boss (when the boss is defeated) it happened to me again, i will test more dungeons and trials to see if it happens

Also it seems that every time i open the game the data editor resets to default

**Comment by shaeeee** [comment]
Thanks for the report, I'll look into it. I haven't had any issues myself so I'm wondering if it might be a difference in hardware.

Another question, does it happen with any custom appearance values? In case there is some specific value that breaks stuff that I have missed to add a check for.

**Comment by Megasder** [comment]
Hi, sorry for all the trouble, but I closed the game and booted it up again and dalamud updated and now works fine. Instead of closing this issue I will test it for a few days, if I see its all good I close the issue.

**Comment by Megasder** [comment]
Oka after trying for some days it has 2 major bugs:
1-The invisible character after cinematic in dungeons/raids
2-After closing the game the config resets to default

the best way to test the first problem is going to the map dungeons, every time you try to open a door the cinematic happens and after that my character becomes invisible except weapon (Notes: during the cinematic it still works fine, so maybe a fix is to automatically update the character model like when you are changing map/instance. If you are invisible and you exit the dungeon/raid your character becomes visible again, it only makes you invisible if, after the cinematic, you are in the same place as when you were before the cinematic) (Also while doing a dungeon and being invisible I repaired my armor, the animation to repair the armor made my character visible again)

for the second problem it only happens after you exit the game only, if you log out and enter again it still remembers the settings that you put before.

**Comment by shaeeee** [comment]
Can you send me a picture of what the configuration window looks before and after your character becomes invisible? I don't have your issue so need anything I can get.

**Comment by Megasder** [comment]
Here is the invisible
![image](https://user-images.githubusercontent.com/92712466/168924520-154accee-9e6b-4f05-8b30-a3b5cc68c028.png)

Here is the visible
![image](https://user-images.githubusercontent.com/92712466/168924591-0a3ca72d-3eb5-44ec-a53f-7e39d42186f2.png)

I don't see any differences... however now I know something new, I only become invisible when im doing content with other people (or maybe when im synced to low level).  I noticed it because to test if the plugin work I unsynced run a dungeon solo, if I do this the plugin works fine. But if I do the same dungeon with other people (like doing the daily roulettes) my character becomes invisible after a cinematic, maybe that is why it works on your end, because you tried it unsynced.

**Comment by shaeeee** [comment]
Thanks for the images. My own testing has been in completely normal gameplay: alliance raids, synced content, unsynced content, treasure maps, and yet nothing. The only thing that strikes me as odd about your config is perhaps your Eyeshape, since its normally something around 0-5. However, I tested your exact configuration and found no issues with that either. 

From doing some research, it might be a latency issue, where the game will try to avoid reloading characters or something, but I don't know for sure. Do you happen to have high ping by any chance?

While I think of a fix, if you do end up invisible you can try using the command "/cv r" without quotation marks to force a character reload, which should fix the invisibility issue, at least until it happens again. 

PS: I may have found the issue. I'm shooting blindly here but maybe it works for you, I'll upload a new release soon.
Edit: soon meaning 5 minutes after this was posted

**Comment by Megasder** [comment]
Wow it works perfect now, thank you :D closing the issue since it seems to be resolved
